/*
 * This file is generated by jOOQ.
 */
package orm.jooq;


import javax.annotation.Generated;

import orm.jooq.tables.Authors;
import orm.jooq.tables.Books;
import orm.jooq.tables.Projects;
import orm.jooq.tables.Tasks;
import orm.jooq.tables.UserToProject;
import orm.jooq.tables.Users;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.authors</code>.
     */
    public static final Authors AUTHORS = orm.jooq.tables.Authors.AUTHORS;

    /**
     * The table <code>PUBLIC.books</code>.
     */
    public static final Books BOOKS = orm.jooq.tables.Books.BOOKS;

    /**
     * The table <code>PUBLIC.projects</code>.
     */
    public static final Projects PROJECTS = orm.jooq.tables.Projects.PROJECTS;

    /**
     * The table <code>PUBLIC.tasks</code>.
     */
    public static final Tasks TASKS = orm.jooq.tables.Tasks.TASKS;

    /**
     * The table <code>PUBLIC.user_to_project</code>.
     */
    public static final UserToProject USER_TO_PROJECT = orm.jooq.tables.UserToProject.USER_TO_PROJECT;

    /**
     * The table <code>PUBLIC.users</code>.
     */
    public static final Users USERS = orm.jooq.tables.Users.USERS;
}
