spring:
  datasource:
    url: jdbc:h2:~/orm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;MODE=MYSQL;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    continue-on-error: true
  h2:
    console:
      enabled: true