CREATE TABLE IF NOT EXISTS authors (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
  id INT NOT NULL AUTO_INCREMENT,
  author_id INT NOT NULL,
  name VARCHAR(50) NOT NULL,
  FOREIGN KEY (id) REFERENCES authors(id) ON DELETE CASCADE
);
