/*
 * This file is generated by jOOQ.
 */
package orm.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import orm.jooq.tables.Authors;
import orm.jooq.tables.Books;
import orm.jooq.tables.records.AuthorsRecord;
import orm.jooq.tables.records.BooksRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthorsRecord, Integer> IDENTITY_AUTHORS = Identities0.IDENTITY_AUTHORS;
    public static final Identity<BooksRecord, Integer> IDENTITY_BOOKS = Identities0.IDENTITY_BOOKS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<BooksRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BooksRecord, AuthorsRecord> CONSTRAINT_59 = ForeignKeys0.CONSTRAINT_59;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AuthorsRecord, Integer> IDENTITY_AUTHORS = Internal.createIdentity(Authors.AUTHORS, Authors.AUTHORS.ID);
        public static Identity<BooksRecord, Integer> IDENTITY_BOOKS = Internal.createIdentity(Books.BOOKS, Books.BOOKS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorsRecord> CONSTRAINT_D = Internal.createUniqueKey(Authors.AUTHORS, "constraint_d", Authors.AUTHORS.ID);
        public static final UniqueKey<BooksRecord> CONSTRAINT_5 = Internal.createUniqueKey(Books.BOOKS, "constraint_5", Books.BOOKS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BooksRecord, AuthorsRecord> CONSTRAINT_59 = Internal.createForeignKey(orm.jooq.Keys.CONSTRAINT_D, Books.BOOKS, "constraint_59", Books.BOOKS.AUTHOR_ID);
    }
}
