/*
 * This file is generated by jOOQ.
 */
package orm.jooq;


import javax.annotation.Generated;

import orm.jooq.tables.Authors;
import orm.jooq.tables.Books;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.authors</code>.
     */
    public static final Authors AUTHORS = orm.jooq.tables.Authors.AUTHORS;

    /**
     * The table <code>PUBLIC.books</code>.
     */
    public static final Books BOOKS = orm.jooq.tables.Books.BOOKS;
}
